# Generated by Django 4.2.6 on 2023-10-16 10:19

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('icon', models.FileField(upload_to='podcast/icons/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Podcast Category',
                'verbose_name_plural': 'Podcast Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=400, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='podcast/comments/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Podcast Comment',
                'verbose_name_plural': 'Podcast Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=400, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Podcast Comment Complaint',
                'verbose_name_plural': 'Podcast Comment Complaints',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('subtitle_uz', models.CharField(max_length=255, null=True, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(max_length=255, null=True, verbose_name='Subtitle')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Body')),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body')),
                ('status', models.CharField(choices=[('dr', 'Draft'), ('im', 'In moderation'), ('pb', 'Published')], max_length=2, verbose_name='Status')),
                ('cover', models.ImageField(default='default_podcast_cover.png', upload_to='podcast/covers/', verbose_name='Cover')),
                ('file', models.FileField(upload_to='podcast/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4a', 'wav'])], verbose_name='File')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
