# Generated by Django 4.2.6 on 2023-10-06 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "icon",
                    models.FileField(upload_to="podcast/icons/", verbose_name="Icon"),
                ),
            ],
            options={
                "verbose_name": "Podcast Category",
                "verbose_name_plural": "Podcast Categories",
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255, verbose_name="Slug")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("desc", models.TextField(verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View count"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="Like count"),
                ),
                (
                    "dislike_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Dislike count"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        default="default_podcast_cover.png",
                        upload_to="podcast/covers/",
                        verbose_name="Cover",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="podcast/audios/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "mp4a", "wav"]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="podcasts",
                        to="users.profile",
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcasts",
                        to="podcast.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Podcast Tag",
                "verbose_name_plural": "Podcast Tags",
            },
        ),
        migrations.CreateModel(
            name="UserPodcastPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("l", "Liked"), ("d", "Disliked"), ("n", "Neutral")],
                        default="n",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="podcast.podcast",
                        verbose_name="Podcast",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_preferences",
                        to="users.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Podcast Preference",
                "verbose_name_plural": "User Podcast Preferences",
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="tags",
            field=models.ManyToManyField(
                related_name="podcasts", to="podcast.tag", verbose_name="Tags"
            ),
        ),
    ]
