# Generated by Django 4.2.6 on 2023-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="slug",
            field=models.CharField(blank=True, max_length=255, verbose_name="Slug"),
        ),
    ]
