# Generated by Django 4.2.6 on 2023-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
        ),
    ]
