# Generated by Django 4.2.6 on 2023-10-13 15:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_comment_commentcomplaint_profilepodcastcommentlike_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilepodcastlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profilepodcastlike',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='profilepodcastlike',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='view_count',
        ),
        migrations.AddField(
            model_name='podcast',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='body_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='subtitle_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='ProfilePodcastCommentLike',
        ),
        migrations.DeleteModel(
            name='ProfilePodcastLike',
        ),
    ]
