# Generated by Django 4.2.6 on 2023-10-14 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0006_alter_profilepodcastlike_unique_together_and_more"),
        ("podcast", "0006_alter_tag_options_alter_podcast_category_and_more"),
    ]

    operations = []
