# Generated by Django 4.2.6 on 2023-10-16 10:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1200)),
                ('expire_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'BreakingNews',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('desc', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('is_verified', models.BooleanField(blank=True)),
                ('cover', models.ImageField(upload_to='news/cover_images/')),
                ('position', models.CharField(choices=[('main', 'Main'), ('prime', 'Prime'), ('ordinary', 'Ordinary')], default='ordinary', max_length=100, verbose_name='position of news in main site page')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in moderation', 'In moderation'), ('published', 'Published')], default='draft', max_length=100)),
                ('type', models.CharField(choices=[('article', 'Article'), ('news', 'News')], default='news', max_length=100)),
                ('style', models.CharField(choices=[('style 1', 'Style 1'), ('style 2', 'Style 2')], default='style 1', max_length=100, verbose_name='news appearing style in site')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name of category')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCancelReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='the reason of cancel')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
