# Generated by Django 4.2.6 on 2023-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newstag",
            options={"verbose_name_plural": "News Tags"},
        ),
        migrations.RemoveField(
            model_name="newscommentreport",
            name="name",
        ),
        migrations.AddField(
            model_name="news",
            name="position",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("prime", "Prime"),
                    ("ordinary", "Ordinary"),
                ],
                default="ordinary",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in moderation", "In moderation"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newscommentreport",
            name="text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Text"
            ),
        ),
    ]
