# Generated by Django 4.2.6 on 2023-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_newstag_options_remove_newscommentreport_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.CharField(blank=True, max_length=255, verbose_name="Slug"),
        ),
    ]
