# Generated by Django 4.2.6 on 2023-10-06 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0003_alter_news_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breakingnews",
            options={"verbose_name_plural": "BreakingNews"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
