# Generated by Django 4.2.6 on 2023-10-07 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0005_alter_newslike_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="type",
        ),
        migrations.AddField(
            model_name="news",
            name="style",
            field=models.CharField(
                choices=[("style 1", "Style 1"), ("style 2", "Style 2")],
                default="style 1",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="NewsCancelReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.news"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
