# Generated by Django 4.2.6 on 2023-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_newslike_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(default="", verbose_name="Slug"),
        ),
    ]
