# Generated by Django 4.2.6 on 2023-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_remove_news_type_news_style_newscancelreason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="position",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("prime", "Prime"),
                    ("ordinary", "Ordinary"),
                ],
                default="ordinary",
                max_length=100,
                verbose_name="position of news in main site page",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="style",
            field=models.CharField(
                choices=[("style 1", "Style 1"), ("style 2", "Style 2")],
                default="style 1",
                max_length=100,
                verbose_name="news appearing style in site",
            ),
        ),
        migrations.AlterField(
            model_name="newscancelreason",
            name="text",
            field=models.TextField(verbose_name="the reason of cancel"),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name of category"),
        ),
        migrations.AlterField(
            model_name="newstag",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name of tag"),
        ),
    ]
