# Generated by Django 4.2.6 on 2023-10-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='news.newscomment', verbose_name='Parent'),
        ),
    ]
