# Generated by Django 4.2.6 on 2023-10-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_news_position_alter_news_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsview",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_view_to_news",
                to="news.news",
            ),
        ),
    ]
