# Generated by Django 4.2.6 on 2023-10-09 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_news_desc"),
        ("news", "0009_alter_newscomment_news"),
    ]

    operations = []
