# Generated by Django 4.2.6 on 2023-10-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_merge_20231009_1250"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="type",
            field=models.CharField(
                choices=[("article", "Article"), ("news", "News")],
                default="news",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newscomment",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="news.newscomment",
                verbose_name="Parent",
            ),
        ),
    ]
