# Generated by Django 4.2.6 on 2023-10-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newscomment_parent'),
        ('news', '0011_news_type_alter_newscomment_parent'),
    ]

    operations = [
    ]
