# Generated by Django 4.2.6 on 2023-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0011_news_type_alter_newscomment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_verified",
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
