# Generated by Django 4.2.6 on 2023-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0013_alter_news_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="tag",
            field=models.ManyToManyField(
                related_name="news_to_tags", to="news.newstag"
            ),
        ),
        migrations.AlterField(
            model_name="newstag",
            name="name",
            field=models.CharField(verbose_name="name of tag"),
        ),
    ]
