# Generated by Django 4.2.6 on 2023-10-10 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0014_alter_news_tag_alter_newstag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="tag",
            new_name="tags",
        ),
    ]
