# Generated by Django 4.2.6 on 2023-10-10 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0012_merge_20231010_1031"),
        ("news", "0018_alter_newslike_news"),
    ]

    operations = []
