# Generated by Django 4.2.6 on 2023-10-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_merge_20231010_1700'),
        ('news', '0020_alter_newscomment_parent'),
    ]

    operations = [
    ]
