# Generated by Django 4.2.6 on 2023-10-16 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Review Category',
                'verbose_name_plural': 'Review Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/comment_images', verbose_name='Image')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('liked', models.IntegerField(default=0, verbose_name='Liked')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comment like',
                'verbose_name_plural': 'Comment likes',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('desc', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('desc_uz', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description')),
                ('desc_ru', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description')),
                ('desc_en', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('subtitle_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/images', verbose_name='Image')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='review/covers', verbose_name='Cover')),
                ('liked', models.IntegerField(default=0, verbose_name='Liked')),
                ('view', models.IntegerField(default=0, verbose_name='View')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
