# Generated by Django 4.2.6 on 2023-10-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_contentlike"),
        ("review", "0003_review_desc_en_review_desc_ru_review_desc_uz_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewliked",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reviewliked",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewliked",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="reviewview",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reviewview",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewview",
            name="user",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterField(
            model_name="review",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="common.tag", verbose_name="Tags"
            ),
        ),
        migrations.DeleteModel(
            name="ReviewLiked",
        ),
        migrations.DeleteModel(
            name="ReviewView",
        ),
    ]
