# Generated by Django 4.2.6 on 2023-10-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_desc_en_review_desc_ru_review_desc_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title_ru',
        ),
    ]
