# Generated by Django 4.2.6 on 2023-10-14 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_alter_reviewliked_unique_together_and_more"),
        ("review", "0005_review_desc_en_review_desc_ru_review_subtitle_en_and_more"),
    ]

    operations = []
