# Generated by Django 4.2.6 on 2023-10-14 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_merge_20231014_1118"),
        ("review", "0006_merge_20231014_1122"),
        ("review", "0006_merge_20231014_1255"),
    ]

    operations = []
