# Generated by Django 4.2.6 on 2023-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='advertising',
            name='type',
            field=models.CharField(choices=[('banner', 'Banner'), ('banner2', 'Banner 2'), ('pr_article', 'Pr Article'), ('full_screen', 'Full Screen')], default='banner', max_length=55, verbose_name='Type'),
        ),
    ]
