# Generated by Django 4.2.6 on 2023-10-12 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_contentview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentview",
            options={},
        ),
        migrations.AddField(
            model_name="contentview",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_view",
                to="contenttypes.contenttype",
                verbose_name="Content view",
            ),
        ),
        migrations.AddField(
            model_name="contentview",
            name="object_id",
            field=models.PositiveIntegerField(default=1, verbose_name="Object id"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="count_view",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentview",
            unique_together={("content_type", "object_id", "user")},
        ),
        migrations.RemoveField(
            model_name="contentview",
            name="content",
        ),
        migrations.RemoveField(
            model_name="contentview",
            name="device_id",
        ),
    ]
