# Generated by Django 4.2.6 on 2023-10-12 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0003_alter_contentview_options_contentview_content_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentview",
            unique_together={("content_type", "object_id", "user")},
        ),
        migrations.AddField(
            model_name="contentview",
            name="device_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identified device"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentview",
            unique_together={
                ("content_type", "object_id", "device_id"),
                ("content_type", "object_id", "user"),
            },
        ),
    ]
