# Generated by Django 4.2.6 on 2023-10-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0004_alter_contentview_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(verbose_name="Object id")),
                (
                    "status",
                    models.CharField(
                        choices=[("l", "Liked"), ("d", "Disliked"), ("n", "Neutral")],
                        max_length=10,
                        verbose_name="Like status",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_like",
                        to="contenttypes.contenttype",
                        verbose_name="Content like",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_like",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "status", "user")},
            },
        ),
    ]
