# Generated by Django 4.2.6 on 2023-10-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_info_en_profile_info_ru_profile_info_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
