# Generated by Django 4.2.6 on 2023-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='user_image/', verbose_name='Profile Image'),
        ),
    ]
