# Generated by Django 4.2.6 on 2023-10-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='info_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='info_ru',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role_ru',
        ),
    ]
