# Generated by Django 4.2.6 on 2023-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photoreport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photoreport/comment_images",
                verbose_name="Image",
            ),
        ),
    ]
