# Generated by Django 4.2.6 on 2023-10-16 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreportview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report_view', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='photoreportliked',
            name='photo_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report_liked', to='photoreport.photoreport', verbose_name='Photo report'),
        ),
        migrations.AddField(
            model_name='photoreportliked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report_liked', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='tag',
            field=models.ManyToManyField(to='photoreport.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='photo_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='photoreport.photoreport', verbose_name='Photo report'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='photoreport.comment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='photoreport.comment', verbose_name='Parent Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoreport.photoreport', verbose_name='Photo Report'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='photoreportview',
            unique_together={('user', 'photo_report')},
        ),
        migrations.AlterUniqueTogether(
            name='photoreportliked',
            unique_together={('user', 'photo_report')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
    ]
