# Generated by Django 4.2.6 on 2023-10-08 07:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photoreport", "0003_photoreport_desc_en_photoreport_desc_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoreport",
            name="desc",
            field=ckeditor.fields.RichTextField(default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="photoreport",
            name="desc_en",
            field=ckeditor.fields.RichTextField(
                default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="photoreport",
            name="desc_ru",
            field=ckeditor.fields.RichTextField(
                default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="photoreport",
            name="desc_uz",
            field=ckeditor.fields.RichTextField(
                default="", null=True, verbose_name="Description"
            ),
        ),
    ]
