# Generated by Django 4.2.6 on 2023-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "photoreport",
            "0004_alter_photoreport_desc_alter_photoreport_desc_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoreport",
            name="tag",
            field=models.ManyToManyField(to="photoreport.tag", verbose_name="Tags"),
        ),
    ]
