# Generated by Django 4.2.6 on 2023-10-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photoreport", "0005_alter_photoreport_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comment",
                to="photoreport.comment",
                verbose_name="Parent Comment",
            ),
        ),
    ]
