# Generated by Django 4.2.6 on 2023-10-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photoreport", "0006_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoreport",
            name="is_prime",
            field=models.BooleanField(default=False, verbose_name="Is prime"),
        ),
    ]
