# Generated by Django 4.2.6 on 2023-10-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoreport', '0007_photoreport_is_prime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoreport',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='photoreport',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='photoreport',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='photoreport',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='photoreport',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='photoreport',
            name='title_ru',
        ),
    ]
