# Generated by Django 4.2.6 on 2023-10-12 15:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreport', '0008_remove_photoreport_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
