# Generated by Django 4.2.6 on 2023-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("liked", "Liked"),
                            ("disliked", "Disliked"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
