# Generated by Django 4.2.6 on 2023-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0002_interviewlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="slug",
            field=models.CharField(blank=True, max_length=255, verbose_name="Slug"),
        ),
    ]
