# Generated by Django 4.2.6 on 2023-10-12 15:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_interview_desc_en_remove_interview_desc_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='interview',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='interview',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='interview',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='interview',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='interview',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
