# Generated by Django 4.2.6 on 2023-10-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_comment_image_alter_comment_interview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='Liked'),
        ),
        migrations.AddField(
            model_name='interview',
            name='view',
            field=models.IntegerField(default=0, verbose_name='View'),
        ),
    ]
