# Generated by Django 4.2.6 on 2023-10-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interview_liked_interview_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
        ),
    ]
