# Generated by Django 4.2.6 on 2023-10-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_interviewview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='dislike_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dislike count'),
        ),
        migrations.AddField(
            model_name='interview',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Like count'),
        ),
    ]
