# Generated by Django 4.2.6 on 2023-10-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0012_interview_dislike_count_interview_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewlike',
            name='profile',
        ),
        migrations.AddField(
            model_name='interviewlike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_user_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
