# Generated by Django 4.2.6 on 2023-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_tag"),
        ("interview", "0014_comment_delete_interviewlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InterviewTag",
        ),
        migrations.AlterField(
            model_name="interview",
            name="tag",
            field=models.ManyToManyField(
                related_name="interview_tag", to="common.tag", verbose_name="Tag"
            ),
        ),
    ]
